<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2025/blob/main/IMT_P3_2025_1_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->


# **Avaliação P3**: Regressão e Classificação, Métricas

Explore os dados abaixo e a seguir implemente modelos de regressão e classificação.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
path = 'https://github.com/Rogerio-mack/IMT_CD_2025/raw/refs/heads/main/data/'

In [ ]:
df = pd.read_csv(path + 'credit_card_data.csv')
print("Dados para o aprendizado do modelo...")
display(df.head())
print()

df_case_regression = pd.read_csv(path + 'credit_card_data_case_regression.csv')
print("Dados para predição de `expenditure`")
display(df_case_regression.head())
print()

df_case_classification = pd.read_csv(path + 'credit_card_data_case_classification.csv')
print("Dados para predição de `card`")
display(df_case_classification.head())
print()

dfo, dfro, dfco = df.copy(), df_case_regression.copy(), df_case_classification.copy()

def gera_data(case,seed,n_medium=20,n_null=5):
  # data 1
  df, df_case_regression, df_case_classification = dfo.copy(), dfro.copy(), dfco.copy()

  df['card'] = df['card'].map({'yes': 'high', 'no': 'low'})
  df_case_regression['card'] = df_case_regression['card'].map({'yes': 'high', 'no': 'low'})
  df.loc[df[df['card'] == 'high'].sample(n=n_medium, random_state=seed).index, 'card'] = 'medium'

  df.loc[df.sample(n=n_null, random_state=seed).index, 'months'] = np.nan

  df_case_regression.client_name = df.client_name.sample(n=3, random_state=seed).values
  df_case_classification.client_name = df.client_name.sample(n=3, random_state=seed+10).values

  df_case_classification.loc[case-1] = df.iloc[1310+case].drop(columns=['card'])
  df_case_classification.loc[(case+1)%3, 'months'] = np.nan

  df.to_csv(f'credit_card_data_{case}.csv', index=False)
  df_case_regression.to_csv(f'credit_card_data_case_regression_{case}.csv', index=False)
  df_case_classification.to_csv(f'credit_card_data_case_classification_{case}.csv', index=False)

  print("\nDados para o aprendizado do modelo...")
  display(df.head())
  print()

  print("Dados para predição de `expenditure`")
  display(df_case_regression.head())
  print()

  print("Dados para predição de `card`")
  display(df_case_classification.head())
  print()

  print('\nExceptions...')
  print(df[df['card'] == 'medium'].index)
  print(df[df.months.isna()].index)


gera_data(1,42,n_medium=20,n_null=5)
gera_data(2,1,n_medium=15,n_null=4)
gera_data(3,1942,n_medium=19,n_null=5)



Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  yes        0   37    4.52   0.03       124.98   yes      no           3   
1  yes        0   33    2.42   0.01         9.85    no      no           3   
2  yes        0   33    4.50   0.00        15.00   yes      no           4   
3  yes        0   30    2.54   0.07       137.87    no      no           0   
4  yes        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0      54           1      12      Ivan Gomez          Male  
1      34           1      13   Sean Williams  Not Declared  
2      58           1       5   William Beard          Male  
3      25           1       7  Cynthia Cuevas        Female  
4      64           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  yes        0   32    3.37   0.07    no      no           0      55   
1  yes        0   25    2.24   0.00    no      no           0      12   
2  yes        1   46    5.50   0.18    no      no           3     143   

   majorcards  active          client_name     sex  
0           0       6  Christopher Huffman    Male  
1           1       2    Jennifer Mitchell  Female  
2           1      16         James Massey    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0      55   
1        0   25    2.24   0.00         4.58    no     yes           0      12   
2        0   41    1.98   0.00         2.20   yes      no           2      36   

   majorcards  active       client_name           sex  
0           0       6       Joseph Reid          Male  
1           1       2  Lindsey Gonzales  Not Declared  
2           1       0    Linda Berkeley        Female



Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active    client_name     sex  
0           0       6   Stacy Gibson    Male  
1           1       2   Larry Wagner  Female  
2           1      16  Lauren Nelson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   39    2.30    0.0         0.00    no     yes           0    46.0   
1        0   25    2.24    0.0         4.58    no     yes           0    12.0   
2        0   41    1.98    0.0         2.20   yes      no           2     NaN   

   majorcards  active     client_name           sex  
0           1       3    George Smith          Male  
1           1       2  Matthew Maddox  Not Declared  
2           1       0   Ashley Cooper        Female



Exceptions...
Index([ 40,  97, 105, 136, 374, 467, 486, 525, 554, 573, 577, 677, 761, 797,
       801, 838, 870, 923, 946, 963],
      dtype='int64')
Index([49, 610, 677, 1046, 1284], dtype='int64')

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active      client_name     sex  
0           0       6       Lori Adams    Male  
1           1       2     Ann Hamilton  Female  
2           1      16  James Mcpherson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0     NaN   
1        0   22    3.86   0.00         0.00    no      no           1    36.0   
2        0   41    1.98   0.00         2.20   yes      no           2    36.0   

   majorcards  active       client_name     sex  
0           0       6      Kevin Hunter    Male  
1           0       4  Catherine Turner  Female  
2           1       0      Jeremy Pratt  Female



Exceptions...
Index([35, 139, 316, 423, 524, 652, 772, 829, 853, 888, 983, 1045, 1194, 1195,
       1242],
      dtype='int64')
Index([190, 288, 596, 852], dtype='int64')

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active    client_name     sex  
0           0       6  Gary Williams    Male  
1           1       2    Jill Flores  Female  
2           1      16   Johnny Jones    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0    55.0   
1        0   25    2.24   0.00         4.58    no     yes           0     NaN   
2        1   30    2.18   0.00         0.00    no     yes           0    13.0   

   majorcards  active    client_name           sex  
0           0       6  Jason Ramirez          Male  
1           1       2     Eric Simon  Not Declared  
2           1       1    Julian Choi          Male



Exceptions...
Index([ 124,  156,  261,  286,  387,  388,  419,  466,  489,  556,  590,  713,
        729,  772,  916,  958, 1079, 1140, 1224],
      dtype='int64')
Index([48, 314, 467, 758, 909], dtype='int64')


In [ ]:
%%script echo off
!rm *

off


In [ ]:
%%script echo off
from google.colab import files

# List of generated files to download
generated_files = [
    'credit_card_data_1.csv',
    'credit_card_data_case_regression_1.csv',
    'credit_card_data_case_classification_1.csv',
    'credit_card_data_2.csv',
    'credit_card_data_case_regression_2.csv',
    'credit_card_data_case_classification_2.csv',
    'credit_card_data_3.csv',
    'credit_card_data_case_regression_3.csv',
    'credit_card_data_case_classification_3.csv'
]

for file_name in generated_files:
  try:
    files.download(file_name)
  except FileNotFoundError:
    print(f"File not found: {file_name}")

off


In [ ]:
path = ''
case = 1

df = pd.read_csv(path + f'credit_card_data_{case}.csv')
print("Dados para o aprendizado do modelo...")
display(df.head())
print()

df_case_regression = pd.read_csv(path + f'credit_card_data_case_regression_{case}.csv')
print("Dados para predição de `expenditure`")
display(df_case_regression.head())
print()

df_case_classification = pd.read_csv(path + f'credit_card_data_case_classification_{case}.csv')
print("Dados para predição de `card`")
display(df_case_classification.head())
print()

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active    client_name     sex  
0           0       6   Stacy Gibson    Male  
1           1       2   Larry Wagner  Female  
2           1      16  Lauren Nelson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   39    2.30    0.0         0.00    no     yes           0    46.0   
1        0   25    2.24    0.0         4.58    no     yes           0    12.0   
2        0   41    1.98    0.0         2.20   yes      no           2     NaN   

   majorcards  active     client_name           sex  
0           1       3    George Smith          Male  
1           1       2  Matthew Maddox  Not Declared  
2           1       0   Ashley Cooper        Female

# Exercício 1. Regressão.

Faça um modelo de regressão linear para estimar novos valores de `expenditure` a partir dos **demais atributos preditores** que sejam **significativos**. Para atributos categóricos considere significativos **somente atributos em que todos os encodes forem significativos**.

- **Valores ausentes** deve ser substituídos por valores com a mesma distribuição dentro do gênero (sexo). Empregue o seed=42 para seleção aleatória de valores a serem imputados.

Em seguida faça um modelo robusto indicado e compare os resultados.



## 1.1. Qual o $R2$ obtido pelo modelo de regressão linear somente com os atributos **preditores significativos**?



In [ ]:
df[ df.isna().any(axis=1) ]

card  reports  age  income  share  expenditure owner selfemp  \
49      high        0   27    7.00   0.11       644.83   yes      no   
610     high        0   36    3.00   0.03        80.83   yes      no   
677   medium        0   32    1.81   0.05        81.44   yes      no   
1046    high        0   23    2.00   0.10       166.90    no      no   
1284    high        0   49    3.11   0.01        21.46   yes      no   

      dependents  months  majorcards  active       client_name     sex  
49             0     NaN           1      13    Bobby Odonnell    Male  
610            3     NaN           0       4     Lauren Nelson  Female  
677            0     NaN           1      22      Stacy Gibson  Female  
1046           0     NaN           1       0      Larry Wagner    Male  
1284           1     NaN           0       6  Joseph Carpenter    Male

In [ ]:
np.random.seed(42)
c = 'months'
display(df[ df.isna().any(axis=1) ])

for sex in df.sex.unique():

  isna_by_sex = (df[c].isna()) & (df['sex'] == sex)
  notna_by_sex = (~df[c].isna()) & (df['sex'] == sex)

  non_null_values = df[notna_by_sex][c]

  # Use np.random.choice with replacement to sample from non_null_values
  sampled_values = np.random.choice(non_null_values, size=sum(isna_by_sex), replace=True)

  # Fill the NaN values in the 'age' column with the sampled values
  df.loc[isna_by_sex, c] = sampled_values

print('\nAfter')
display(df[ df.isna().any(axis=1) ])

card  reports  age  income  share  expenditure owner selfemp  \
49      high        0   27    7.00   0.11       644.83   yes      no   
610     high        0   36    3.00   0.03        80.83   yes      no   
677   medium        0   32    1.81   0.05        81.44   yes      no   
1046    high        0   23    2.00   0.10       166.90    no      no   
1284    high        0   49    3.11   0.01        21.46   yes      no   

      dependents  months  majorcards  active       client_name     sex  
49             0     NaN           1      13    Bobby Odonnell    Male  
610            3     NaN           0       4     Lauren Nelson  Female  
677            0     NaN           1      22      Stacy Gibson  Female  
1046           0     NaN           1       0      Larry Wagner    Male  
1284           1     NaN           0       6  Joseph Carpenter    Male


After


Empty DataFrame
Columns: [card, reports, age, income, share, expenditure, owner, selfemp, dependents, months, majorcards, active, client_name, sex]
Index: []

In [ ]:
import statsmodels.formula.api as sm

formula = 'expenditure ~ ' + ' + '.join(df.drop(['expenditure','client_name'],axis=1).columns.tolist())

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())


                            OLS Regression Results                            
Dep. Variable:            expenditure   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.810
Method:                 Least Squares   F-statistic:                     402.6
Date:                Mon, 06 Oct 2025   Prob (F-statistic):               0.00
Time:                        11:45:52   Log-Likelihood:                -8163.6
No. Observations:                1319   AIC:                         1.636e+04
Df Residuals:                    1304   BIC:                         1.644e+04
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept            -181.7769    

In [ ]:
p_values = results.pvalues

significant_variables = p_values[p_values < 0.05]

print(significant_variables)


Intercept       4.924789e-30
sex[T.Male]     3.738027e-02
income         1.778553e-101
share           0.000000e+00
months          1.784514e-02
dtype: float64


In [ ]:
import statsmodels.formula.api as sm

formula = 'expenditure ~ ' + ' + '.join(['income', 'share', 'months'])

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())

                            OLS Regression Results                            
Dep. Variable:            expenditure   R-squared:                       0.810
Model:                            OLS   Adj. R-squared:                  0.810
Method:                 Least Squares   F-statistic:                     1873.
Date:                Mon, 06 Oct 2025   Prob (F-statistic):               0.00
Time:                        11:45:52   Log-Likelihood:                -8169.7
No. Observations:                1319   AIC:                         1.635e+04
Df Residuals:                    1315   BIC:                         1.637e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -155.7934      8.011    -19.447      0.0

## 1.2. Qual a predição de despesas (`expenditure`) dos clientes da base `credit_card_data_case_regression`?

In [ ]:
df_case_regression['expenditure_prev'] = results.predict(df_case_regression)
display(df_case_regression[['client_name','expenditure_prev']])

print("\nCase:", case)

client_name  expenditure_prev
0   Stacy Gibson        188.991142
1   Larry Wagner        -38.335389
2  Lauren Nelson        562.975340


Case: 1


## 1.3. Você pode notar que a previsão de despesas de `Larry Wagner` foi negativa. Não faz sentido um valor de despesa negativo. Como você pode corrigir isso? Qual a nova predição da despesa de `Larry Wagner`?

In [ ]:
formula = 'expenditure ~ ' + ' + '.join(['income', 'share', 'months']) + '-1'

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())

df_case_regression['expenditure_prev'] = results.predict(df_case_regression)
display(df_case_regression[['client_name','expenditure_prev']])

                                 OLS Regression Results                                
Dep. Variable:            expenditure   R-squared (uncentered):                   0.833
Model:                            OLS   Adj. R-squared (uncentered):              0.833
Method:                 Least Squares   F-statistic:                              2189.
Date:                Mon, 06 Oct 2025   Prob (F-statistic):                        0.00
Time:                        11:45:52   Log-Likelihood:                         -8336.4
No. Observations:                1319   AIC:                                  1.668e+04
Df Residuals:                    1316   BIC:                                  1.669e+04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

client_name  expenditure_prev
0   Stacy Gibson        214.488558
1   Larry Wagner         47.694370
2  Lauren Nelson        477.841698

## 1.4. Empregue agora um modelo equivalente (mesmos regressores) mais robusto, o `Ridge Regressor`. Qual o seu **$R2$**? É maior que o anterior? Qual o valor de despesa de `Larry Wagner` nesse novo modelo?

In [ ]:
from sklearn.linear_model import HuberRegressor, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

# Split data into training and testing sets for regression
X = df[['income', 'share', 'months']] # Select the significant features
y = df['expenditure']

# Robust Regression (Huber Regressor)
huber = HuberRegressor(fit_intercept=False)
huber.fit(X, y)
y_pred_huber = huber.predict(X)
r2_huber = r2_score(y, y_pred_huber)
print(f"R2 score for Huber Regressor: {r2_huber:.4f}")

# Ridge Regression
ridge = Ridge(fit_intercept=False)
ridge.fit(X, y)
y_pred_ridge = ridge.predict(X)
r2_ridge = r2_score(y, y_pred_ridge)
print(f"R2 score for Ridge Regressor: {r2_ridge:.4f}")

# Compare with OLS R2 from previous steps
# You can get the R2 from the OLS results object 'results' in the previous cell 'jMHZvJ-vlKM9'
ols_r2 = results.rsquared # Access R-squared from the OLS results
print(f"R2 score for OLS: {ols_r2:.4f}")

# Predict for the case data using the new models
df_case_regression_selected = df_case_regression[['income', 'share', 'months']] # Select the same features

df_case_regression['expenditure_prev_huber'] = huber.predict(df_case_regression_selected)
df_case_regression['expenditure_prev_ridge'] = ridge.predict(df_case_regression_selected)

df_case_regression['expenditure_prev_OLS'] = results.predict(df_case_regression)

print("\nPredictions for the case data:")
display(df_case_regression[['client_name', 'expenditure_prev_OLS', 'expenditure_prev_huber', 'expenditure_prev_ridge']])

R2 score for Huber Regressor: 0.7205
R2 score for Ridge Regressor: 0.7526
R2 score for OLS: 0.8330

Predictions for the case data:


client_name  expenditure_prev_OLS  expenditure_prev_huber  \
0   Stacy Gibson            214.488558              172.167014   
1   Larry Wagner             47.694370               17.549423   
2  Lauren Nelson            477.841698              416.185401   

   expenditure_prev_ridge  
0              211.906633  
1               52.868272  
2              464.081787

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate RMSE for OLS model on X_train
y_pred_ols_train = results.predict(X)
rmse_ols_train = np.sqrt(mean_squared_error(y, y_pred_ols_train))
print(f"RMSE for OLS on Training Data: {rmse_ols_train:.4f}")

# Calculate RMSE for Huber Regressor on X_train
y_pred_huber_train = huber.predict(X)
rmse_huber_train = np.sqrt(mean_squared_error(y, y_pred_huber_train))
print(f"RMSE for Huber Regressor on Training Data: {rmse_huber_train:.4f}")

# Calculate RMSE for Ridge Regressor on X_train
y_pred_ridge_train = ridge.predict(X)
rmse_ridge_train = np.sqrt(mean_squared_error(y, y_pred_ridge_train))
print(f"RMSE for Ridge Regressor on Training Data: {rmse_ridge_train:.4f}")



RMSE for OLS on Training Data: 134.4646
RMSE for Huber Regressor on Training Data: 143.8489
RMSE for Ridge Regressor on Training Data: 135.3553


# Exercício 2. Classificação.

Implemente um modelo de `Regressão Logística` e um de `Árvore de Decisão` para a classificação da classe `card` empregando os **4 atributos preditores com maior ganho de informação** (informação mútua, empregando `random_state=42` para calcular).

* **Valores ausentes**. Segue mesma lógica de substituição do exercício anterior, incluindo o `seed=42`.

* **Normalização**. Em ambos os casos normalize os dados com a normalização `Standard Scaler`.

* **Conjuntos de Treinamento e Teste**. Empregue 25% de dados de teste, mantendo nos conjuntos a mesma distribuição dos valores de `card` e `random_state=42`.

* **Outros parâmetros**. Na **Árvore de Decisão**, empregue `random_state=42`, e na **Regressão Logística**, `max_iter=1000`. Mantenha os demais parâmetros inalterados.





### 2.1. Quais os atributos com maior ganho de informação selecionados e quais são os seus valores?



In [ ]:
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Separate features (X) and target (y)
X = df.drop(['card', 'client_name'], axis=1)
y = df['card']

# Identify categorical features
categorical_cols = X.select_dtypes(include=['object']).columns

# Apply one-hot encoding to categorical features for mutual information calculation
# We use get_dummies here for simplicity in this specific context,
# not necessarily for downstream model training.
for c in categorical_cols:
    X[c] = LabelEncoder().fit_transform(X[c])

# Calculate mutual information scores
mutual_info = mutual_info_classif(X, y, random_state=42)

# Create a pandas Series for better visualization of scores
mutual_info_series = pd.Series(mutual_info, index=X.columns)

# Sort the scores in descending order
mutual_info_series.sort_values(ascending=False, inplace=True)

# Display the mutual information scores
print("Mutual Information Scores for features:")
display(mutual_info_series)

Mutual Information Scores for features:


expenditure    0.469497
share          0.396884
reports        0.119934
months         0.022714
income         0.016622
age            0.009821
majorcards     0.006571
dependents     0.004953
owner          0.003726
selfemp        0.000000
active         0.000000
sex            0.000000
dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

predictors = list(mutual_info_series.index[0:4])
X = df[predictors]
y = df['card']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.25, random_state=42)
X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(X_train)
X_train = pd.DataFrame(scaled_data, columns=X_train.columns)

scaled_data = scaler.transform(X_test)
X_test = pd.DataFrame(scaled_data, columns=X_test.columns)

display(X_train.head())
display(X_test.head())

expenditure     share   reports    months
0    -0.009898  0.422782 -0.348542 -0.715351
1    -0.668424 -0.723639 -0.348542 -0.308097
2     1.217325  1.464982 -0.348542 -0.747931
3    -0.163265  0.318561 -0.348542 -0.470998
4    -0.426853 -0.515199 -0.348542 -0.177775

expenditure     share   reports    months
0    -0.547709 -0.515199 -0.348542 -0.063744
1    -0.668424 -0.723639 -0.348542  0.799634
2    -0.273273 -0.202539 -0.348542 -0.764221
3     0.746692  1.256542 -0.348542 -0.666480
4    -0.219206  0.005901 -0.348542  2.868485

### 2.2. Qual a acuracidade de cada um dos modelos obtidos e qual o **melhor modelo** (critério de acuracidade)?



### 2.3. No **pior modelo** (critério de acuracidade), qual valor de classe apresenta mais Falsos Positivos, e qual é essa quantidade?

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# Initialize the models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'KNN k=6': KNeighborsClassifier(n_neighbors=6),
    'Decision Tree': DecisionTreeClassifier(random_state=42)
}

# Train and evaluate each model
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy
    print(f'{name} Accuracy: {accuracy:.4f}')
    confusion = confusion_matrix(y_test, y_pred)
    print("\nMatriz de Confusão:\n", confusion)
    print()
    print(classification_report(y_test, y_pred))

# Optional: Print the best model
best_model_name = max(results, key=results.get)
print(f'\nBest model based on accuracy: {best_model_name}')

Logistic Regression Accuracy: 0.8758

Matriz de Confusão:
 [[219  32   0]
 [  4  70   0]
 [  5   0   0]]

              precision    recall  f1-score   support

        high       0.96      0.87      0.91       251
         low       0.69      0.95      0.80        74
      medium       0.00      0.00      0.00         5

    accuracy                           0.88       330
   macro avg       0.55      0.61      0.57       330
weighted avg       0.88      0.88      0.87       330

KNN k=6 Accuracy: 0.8879

Matriz de Confusão:
 [[228  23   0]
 [  9  65   0]
 [  5   0   0]]

              precision    recall  f1-score   support

        high       0.94      0.91      0.92       251
         low       0.74      0.88      0.80        74
      medium       0.00      0.00      0.00         5

    accuracy                           0.89       330
   macro avg       0.56      0.60      0.58       330
weighted avg       0.88      0.89      0.88       330

Decision Tree Accuracy: 0.9394

Matriz

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/m

### 2.4. Qual a predição dos casos de `df_case_classification` empregando o melhor modelo? Qual a probabilidade de cada valor de classe para a predição para `George Smith` e `Matthew Maddox`?

In [ ]:
np.random.seed(42)
c = 'months'
display(df_case_classification[ df_case_classification.isna().any(axis=1) ])

for sex in df_case_classification.sex.unique():

  isna_by_sex = (df_case_classification[c].isna()) & (df['sex'] == sex)
  notna_by_sex = (~df[c].isna()) & (df['sex'] == sex)

  non_null_values = df[notna_by_sex][c]

  # Use np.random.choice with replacement to sample from non_null_values
  sampled_values = np.random.choice(non_null_values, size=sum(isna_by_sex), replace=True)

  # Fill the NaN values in the 'age' column with the sampled values
  df_case_classification.loc[isna_by_sex, c] = sampled_values

display(df_case_classification[ df_case_classification.isna().any(axis=1) ])


reports  age  income  share  expenditure owner selfemp  dependents  months  \
2        0   41    1.98    0.0          2.2   yes      no           2     NaN   

   majorcards  active    client_name     sex  
2           1       0  Ashley Cooper  Female

Empty DataFrame
Columns: [reports, age, income, share, expenditure, owner, selfemp, dependents, months, majorcards, active, client_name, sex]
Index: []

In [ ]:
# Select the same features used for training
X_case_classification = df_case_classification[predictors]

# Scale the case data using the same scaler fitted on the training data
X_case_classification_scaled = scaler.transform(X_case_classification)
X_case_classification_scaled = pd.DataFrame(X_case_classification_scaled, columns=X_case_classification.columns)

# Get the best model (Decision Tree)
best_model = models['Decision Tree']

# Make predictions on the scaled case data
df_case_classification['card_predicted'] = best_model.predict(X_case_classification_scaled)

# Display the client names and their predicted card class
print("Predicted card class for clients in df_case_classification:")
display(df_case_classification[['client_name', 'card_predicted']])

Predicted card class for clients in df_case_classification:


client_name card_predicted
0    George Smith            low
1  Matthew Maddox           high
2   Ashley Cooper           high

In [ ]:
best_model.predict_proba(X_case_classification_scaled)

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

# Teoria

In [ ]:
import numpy as np

# Define the possible categories
categories = ['cat', 'dog', 'bird']
list_size = 200
disagreement_rate = 0.20

# Create the 'Actual' list with random values
np.random.seed(case) # for reproducibility
Actual = np.random.choice(categories, size=list_size, replace=True).tolist()

# Create the 'Predicted' list
Predicted = []
for i in range(list_size):
    if np.random.rand() < disagreement_rate:
        # Choose a different category for predicted
        other_categories = [cat for cat in categories if cat != Actual[i]]
        Predicted.append(np.random.choice(other_categories))
    else:
        # Make predicted match actual
        Predicted.append(Actual[i])

# Optional: Verify the disagreement rate (approximately)
# disagreement_count = sum([1 for a, p in zip(Actual, Predicted) if a != p])
# print(f"Approximate disagreement rate: {disagreement_count / list_size:.2f}")

print("Generated 'Actual' and 'Predicted' lists.")

Generated 'Actual' and 'Predicted' lists.


In [ ]:
confusion_matrix(Actual,Predicted)

array([[39, 11,  3],
       [ 7, 54, 11],
       [ 5,  8, 62]])

In [ ]:
print(classification_report(Actual,Predicted))

              precision    recall  f1-score   support

        bird       0.76      0.74      0.75        53
         cat       0.74      0.75      0.74        72
         dog       0.82      0.83      0.82        75

    accuracy                           0.78       200
   macro avg       0.77      0.77      0.77       200
weighted avg       0.77      0.78      0.77       200



In [ ]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix



In [ ]:
import numpy as np

cm = np.array([[30, 5,  5],
       [ 10, 30, 5],
       [ 5,  0, 30]])

cm

array([[30,  5,  5],
       [10, 30,  5],
       [ 5,  0, 30]])

In [ ]:
from sklearn.metrics import classification_report

# Define class names
target_names = ['left', 'right', 'up']

# Generate classification report from the confusion matrix
# Note: classification_report expects true and predicted labels, not the confusion matrix directly.
# To use the confusion matrix, we can reconstruct dummy true and predicted labels
# that would produce this confusion matrix. This is a bit involved.

# A simpler approach is to use the calculated values from the confusion matrix
# to manually calculate precision, recall, and f1-score for each class.
# However, since the user specifically asked for scikit-learn's classification_report,
# let's assume the confusion matrix was derived from some true and predicted labels.

# If you have the original true and predicted labels that generated this cm,
# you would use:
# print(classification_report(true_labels, predicted_labels, target_names=target_names))

# Since we only have the confusion matrix, we can't directly use classification_report.
# Let's provide the classification report based on the manual calculation using the cm values.

# Extract values from the confusion matrix
# Row represents actual class, column represents predicted class
# cm[i, j] is the number of samples of actual class i that were predicted as class j

# Class 'left' (index 0)
tp_left = cm[0, 0]
fn_left = cm[0, 1] + cm[0, 2]
fp_left = cm[1, 0] + cm[2, 0]
tn_left = cm[1, 1] + cm[1, 2] + cm[2, 1] + cm[2, 2] # Sum of all elements not in row 0 or col 0

# Class 'right' (index 1)
tp_right = cm[1, 1]
fn_right = cm[1, 0] + cm[1, 2]
fp_right = cm[0, 1] + cm[2, 1]
tn_right = cm[0, 0] + cm[0, 2] + cm[2, 0] + cm[2, 2]

# Class 'up' (index 2)
tp_up = cm[2, 2]
fn_up = cm[2, 0] + cm[2, 1]
fp_up = cm[0, 2] + cm[1, 2]
tn_up = cm[0, 0] + cm[0, 1] + cm[1, 0] + cm[1, 1]


# Calculate metrics manually
precision_left = tp_left / (tp_left + fp_left) if (tp_left + fp_left) > 0 else 0
recall_left = tp_left / (tp_left + fn_left) if (tp_left + fn_left) > 0 else 0
f1_left = 2 * (precision_left * recall_left) / (precision_left + recall_left) if (precision_left + recall_left) > 0 else 0

precision_right = tp_right / (tp_right + fp_right) if (tp_right + fp_right) > 0 else 0
recall_right = tp_right / (tp_right + fn_right) if (tp_right + fn_right) > 0 else 0
f1_right = 2 * (precision_right * recall_right) / (precision_right + recall_right) if (precision_right + recall_right) > 0 else 0

precision_up = tp_up / (tp_up + fp_up) if (tp_up + fp_up) > 0 else 0
recall_up = tp_up / (tp_up + fn_up) if (tp_up + fn_up) > 0 else 0
f1_up = 2 * (precision_up * recall_up) / (precision_up + recall_up) if (precision_up + recall_up) > 0 else 0

# Calculate overall accuracy
accuracy = np.sum(np.diag(cm)) / np.sum(cm) if np.sum(cm) > 0 else 0

# Print a formatted report similar to classification_report
print("Manual Classification Report:")
print(f"{'':<10s}{'precision':<10s}{'recall':<10s}{'f1-score':<10s}{'support':<10s}")
print("-" * 50)
print(f"{target_names[0]:<10s}{precision_left:<10.2f}{recall_left:<10.2f}{f1_left:<10.2f}{np.sum(cm[0, :]):<10d}")
print(f"{target_names[1]:<10s}{precision_right:<10.2f}{recall_right:<10.2f}{f1_right:<10.2f}{np.sum(cm[1, :]):<10d}")
print(f"{target_names[2]:<10s}{precision_up:<10.2f}{recall_up:<10.2f}{f1_up:<10.2f}{np.sum(cm[2, :]):<10d}")
print("-" * 50)
print(f"{'accuracy':<10s}{'':<10s}{'':<10s}{accuracy:<10.2f}{np.sum(cm):<10d}")

# Note: To get the exact output of scikit-learn's classification_report,
# you would need the original true and predicted labels.
# The manual calculation above provides the same metrics but the formatting
# might differ slightly.

Manual Classification Report:
          precision recall    f1-score  support   
--------------------------------------------------
left      0.67      0.75      0.71      40        
right     0.86      0.67      0.75      45        
up        0.75      0.86      0.80      35        
--------------------------------------------------
accuracy                      0.75      120       
