<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2025/blob/main/IMT_P3_2025_2_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->


# **Avaliação P3**: Regressão e Classificação, Métricas

Explore os dados abaixo e a seguir implemente modelos de regressão e classificação.

In [ ]:
#@markdown run before
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
path = 'https://github.com/Rogerio-mack/IMT_CD_2025/raw/refs/heads/main/data/'

In [ ]:
df = pd.read_csv(path + 'credit_card_data.csv')
print("Dados para o aprendizado do modelo...")
display(df.head())
print()

df_case_regression = pd.read_csv(path + 'credit_card_data_case_regression.csv')
print("Dados para predição de `expenditure`")
display(df_case_regression.head())
print()

df_case_classification = pd.read_csv(path + 'credit_card_data_case_classification.csv')
print("Dados para predição de `card`")
display(df_case_classification.head())
print()

dfo, dfro, dfco = df.copy(), df_case_regression.copy(), df_case_classification.copy()

def gera_data(case,seed,n_medium=20,n_null=5):
  # data 1
  df, df_case_regression, df_case_classification = dfo.copy(), dfro.copy(), dfco.copy()

  df['card'] = df['card'].map({'yes': 'high', 'no': 'low'})
  df_case_regression['card'] = df_case_regression['card'].map({'yes': 'high', 'no': 'low'})
  df.loc[df[df['card'] == 'high'].sample(n=n_medium, random_state=seed).index, 'card'] = 'medium'

  df.loc[df.sample(n=n_null, random_state=seed).index, 'months'] = np.nan

  df_case_regression.client_name = df.client_name.sample(n=3, random_state=seed).values
  df_case_classification.client_name = df.client_name.sample(n=3, random_state=seed+10).values

  df_case_classification.loc[case-1] = df.iloc[1310+case].drop(columns=['card'])
  df_case_classification.loc[(case+1)%3, 'months'] = np.nan

  df.to_csv(f'credit_card_data_{case}.csv', index=False)
  df_case_regression.to_csv(f'credit_card_data_case_regression_{case}.csv', index=False)
  df_case_classification.to_csv(f'credit_card_data_case_classification_{case}.csv', index=False)

  print("\nDados para o aprendizado do modelo...")
  display(df.head())
  print()

  print("Dados para predição de `expenditure`")
  display(df_case_regression.head())
  print()

  print("Dados para predição de `card`")
  display(df_case_classification.head())
  print()

  print('\nExceptions...')
  print(df[df['card'] == 'medium'].index)
  print(df[df.months.isna()].index)


gera_data(1,42,n_medium=20,n_null=5)
gera_data(2,1,n_medium=15,n_null=4)
gera_data(3,1942,n_medium=19,n_null=5)



Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  yes        0   37    4.52   0.03       124.98   yes      no           3   
1  yes        0   33    2.42   0.01         9.85    no      no           3   
2  yes        0   33    4.50   0.00        15.00   yes      no           4   
3  yes        0   30    2.54   0.07       137.87    no      no           0   
4  yes        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0      54           1      12      Ivan Gomez          Male  
1      34           1      13   Sean Williams  Not Declared  
2      58           1       5   William Beard          Male  
3      25           1       7  Cynthia Cuevas        Female  
4      64           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  yes        0   32    3.37   0.07    no      no           0      55   
1  yes        0   25    2.24   0.00    no      no           0      12   
2  yes        1   46    5.50   0.18    no      no           3     143   

   majorcards  active          client_name     sex  
0           0       6  Christopher Huffman    Male  
1           1       2    Jennifer Mitchell  Female  
2           1      16         James Massey    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0      55   
1        0   25    2.24   0.00         4.58    no     yes           0      12   
2        0   41    1.98   0.00         2.20   yes      no           2      36   

   majorcards  active       client_name           sex  
0           0       6       Joseph Reid          Male  
1           1       2  Lindsey Gonzales  Not Declared  
2           1       0    Linda Berkeley        Female



Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active    client_name     sex  
0           0       6   Stacy Gibson    Male  
1           1       2   Larry Wagner  Female  
2           1      16  Lauren Nelson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   39    2.30    0.0         0.00    no     yes           0    46.0   
1        0   25    2.24    0.0         4.58    no     yes           0    12.0   
2        0   41    1.98    0.0         2.20   yes      no           2     NaN   

   majorcards  active     client_name           sex  
0           1       3    George Smith          Male  
1           1       2  Matthew Maddox  Not Declared  
2           1       0   Ashley Cooper        Female



Exceptions...
Index([ 40,  97, 105, 136, 374, 467, 486, 525, 554, 573, 577, 677, 761, 797,
       801, 838, 870, 923, 946, 963],
      dtype='int64')
Index([49, 610, 677, 1046, 1284], dtype='int64')

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active      client_name     sex  
0           0       6       Lori Adams    Male  
1           1       2     Ann Hamilton  Female  
2           1      16  James Mcpherson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0     NaN   
1        0   22    3.86   0.00         0.00    no      no           1    36.0   
2        0   41    1.98   0.00         2.20   yes      no           2    36.0   

   majorcards  active       client_name     sex  
0           0       6      Kevin Hunter    Male  
1           0       4  Catherine Turner  Female  
2           1       0      Jeremy Pratt  Female



Exceptions...
Index([35, 139, 316, 423, 524, 652, 772, 829, 853, 888, 983, 1045, 1194, 1195,
       1242],
      dtype='int64')
Index([190, 288, 596, 852], dtype='int64')

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active    client_name     sex  
0           0       6  Gary Williams    Male  
1           1       2    Jill Flores  Female  
2           1      16   Johnny Jones    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0    55.0   
1        0   25    2.24   0.00         4.58    no     yes           0     NaN   
2        1   30    2.18   0.00         0.00    no     yes           0    13.0   

   majorcards  active    client_name           sex  
0           0       6  Jason Ramirez          Male  
1           1       2     Eric Simon  Not Declared  
2           1       1    Julian Choi          Male



Exceptions...
Index([ 124,  156,  261,  286,  387,  388,  419,  466,  489,  556,  590,  713,
        729,  772,  916,  958, 1079, 1140, 1224],
      dtype='int64')
Index([48, 314, 467, 758, 909], dtype='int64')


In [ ]:
%%script echo off
!rm *

off


In [ ]:
%%script echo off
from google.colab import files

# List of generated files to download
generated_files = [
    'credit_card_data_1.csv',
    'credit_card_data_case_regression_1.csv',
    'credit_card_data_case_classification_1.csv',
    'credit_card_data_2.csv',
    'credit_card_data_case_regression_2.csv',
    'credit_card_data_case_classification_2.csv',
    'credit_card_data_3.csv',
    'credit_card_data_case_regression_3.csv',
    'credit_card_data_case_classification_3.csv'
]

for file_name in generated_files:
  try:
    files.download(file_name)
  except FileNotFoundError:
    print(f"File not found: {file_name}")

off


In [ ]:
path = ''
case = 2

df = pd.read_csv(path + f'credit_card_data_{case}.csv')
print("Dados para o aprendizado do modelo...")
display(df.head())
print()

df_case_regression = pd.read_csv(path + f'credit_card_data_case_regression_{case}.csv')
print("Dados para predição de `expenditure`")
display(df_case_regression.head())
print()

df_case_classification = pd.read_csv(path + f'credit_card_data_case_classification_{case}.csv')
print("Dados para predição de `card`")
display(df_case_classification.head())
print()

Dados para o aprendizado do modelo...


card  reports  age  income  share  expenditure owner selfemp  dependents  \
0  high        0   37    4.52   0.03       124.98   yes      no           3   
1  high        0   33    2.42   0.01         9.85    no      no           3   
2  high        0   33    4.50   0.00        15.00   yes      no           4   
3  high        0   30    2.54   0.07       137.87    no      no           0   
4  high        0   32    9.79   0.07       546.50   yes      no           2   

   months  majorcards  active     client_name           sex  
0    54.0           1      12      Ivan Gomez          Male  
1    34.0           1      13   Sean Williams  Not Declared  
2    58.0           1       5   William Beard          Male  
3    25.0           1       7  Cynthia Cuevas        Female  
4    64.0           1       5     Julie Davis        Female


Dados para predição de `expenditure`


card  reports  age  income  share owner selfemp  dependents  months  \
0  high        0   32    3.37   0.07    no      no           0      55   
1  high        0   25    2.24   0.00    no      no           0      12   
2  high        1   46    5.50   0.18    no      no           3     143   

   majorcards  active      client_name     sex  
0           0       6       Lori Adams    Male  
1           1       2     Ann Hamilton  Female  
2           1      16  James Mcpherson    Male


Dados para predição de `card`


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0     NaN   
1        0   22    3.86   0.00         0.00    no      no           1    36.0   
2        0   41    1.98   0.00         2.20   yes      no           2    36.0   

   majorcards  active       client_name     sex  
0           0       6      Kevin Hunter    Male  
1           0       4  Catherine Turner  Female  
2           1       0      Jeremy Pratt  Female

# Exercício 1. Regressão.

Faça um modelo de regressão linear para estimar novos valores de `expenditure` a partir dos **demais atributos preditores** que sejam **significativos**. Para atributos categóricos considere significativos **somente atributos em que todos os encodes forem significativos**.

- **Valores ausentes** deve ser substituídos por valores com a mesma distribuição dentro do gênero (sexo). Empregue o seed=42 para seleção aleatória de valores a serem imputados.

Em seguida faça um modelo robusto indicado e compare os resultados.



## 1.1. Qual o $R2$ obtido pelo modelo de regressão linear somente com os atributos **preditores significativos**?



In [ ]:
df[ df.isna().any(axis=1) ]

card  reports  age  income  share  expenditure owner selfemp  dependents  \
190  high        0   24    2.89   0.08       193.07    no      no           0   
288   low        0   22    1.80   0.00         0.00    no      no           0   
596  high        0   40    3.12   0.08       199.00   yes      no           1   
852  high        0   24    2.30   0.37       719.51    no      no           0   

     months  majorcards  active      client_name           sex  
190     NaN           0       0     Ann Hamilton  Not Declared  
288     NaN           0       6       Lori Adams        Female  
596     NaN           1      11  Kevin Middleton          Male  
852     NaN           1       2  James Mcpherson          Male

In [ ]:
np.random.seed(42)
c = 'months'
display(df[ df.isna().any(axis=1) ])

for sex in df.sex.unique():

  isna_by_sex = (df[c].isna()) & (df['sex'] == sex)
  notna_by_sex = (~df[c].isna()) & (df['sex'] == sex)

  non_null_values = df[notna_by_sex][c]

  # Use np.random.choice with replacement to sample from non_null_values
  sampled_values = np.random.choice(non_null_values, size=sum(isna_by_sex), replace=True)

  # Fill the NaN values in the 'age' column with the sampled values
  df.loc[isna_by_sex, c] = sampled_values

print('\nAfter')
display(df[ df.isna().any(axis=1) ])

card  reports  age  income  share  expenditure owner selfemp  dependents  \
190  high        0   24    2.89   0.08       193.07    no      no           0   
288   low        0   22    1.80   0.00         0.00    no      no           0   
596  high        0   40    3.12   0.08       199.00   yes      no           1   
852  high        0   24    2.30   0.37       719.51    no      no           0   

     months  majorcards  active      client_name           sex  
190     NaN           0       0     Ann Hamilton  Not Declared  
288     NaN           0       6       Lori Adams        Female  
596     NaN           1      11  Kevin Middleton          Male  
852     NaN           1       2  James Mcpherson          Male


After


Empty DataFrame
Columns: [card, reports, age, income, share, expenditure, owner, selfemp, dependents, months, majorcards, active, client_name, sex]
Index: []

In [ ]:
import statsmodels.formula.api as sm

formula = 'expenditure ~ ' + ' + '.join(df.drop(['expenditure','client_name'],axis=1).columns.tolist())

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())


                            OLS Regression Results                            
Dep. Variable:            expenditure   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.810
Method:                 Least Squares   F-statistic:                     402.7
Date:                Mon, 06 Oct 2025   Prob (F-statistic):               0.00
Time:                        11:52:00   Log-Likelihood:                -8163.4
No. Observations:                1319   AIC:                         1.636e+04
Df Residuals:                    1304   BIC:                         1.643e+04
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept            -180.8574    

In [ ]:
p_values = results.pvalues

significant_variables = p_values[p_values < 0.05]

print(significant_variables)


Intercept       1.012479e-29
sex[T.Male]     3.580235e-02
income         3.136833e-101
share           0.000000e+00
months          1.556571e-02
dtype: float64


In [ ]:
import statsmodels.formula.api as sm

formula = 'expenditure ~ ' + ' + '.join(['income', 'share', 'months'])

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())

                            OLS Regression Results                            
Dep. Variable:            expenditure   R-squared:                       0.810
Model:                            OLS   Adj. R-squared:                  0.810
Method:                 Least Squares   F-statistic:                     1873.
Date:                Mon, 06 Oct 2025   Prob (F-statistic):               0.00
Time:                        11:52:00   Log-Likelihood:                -8169.6
No. Observations:                1319   AIC:                         1.635e+04
Df Residuals:                    1315   BIC:                         1.637e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -155.6092      8.020    -19.403      0.0

## 1.2. Qual a predição de despesas (`expenditure`) dos clientes da base `credit_card_data_case_regression`?

In [ ]:
df_case_regression['expenditure_prev'] = results.predict(df_case_regression)
display(df_case_regression[['client_name','expenditure_prev']])

print("\nCase:", case)

client_name  expenditure_prev
0       Lori Adams        188.986653
1     Ann Hamilton        -38.191289
2  James Mcpherson        562.681938


Case: 2


## 1.3. Você pode notar que a previsão de despesas de `Ann Hamilton` foi negativa. Não faz sentido um valor de despesa negativo. Como você pode corrigir isso? Qual a nova predição da despesa de `Ann Hamilton`?

In [ ]:
formula = 'expenditure ~ ' + ' + '.join(['income', 'share', 'months']) + '-1'

model = sm.ols(formula=formula, data=df)
results = model.fit()

print(results.summary())

df_case_regression['expenditure_prev'] = results.predict(df_case_regression)
display(df_case_regression[['client_name','expenditure_prev']])

                                 OLS Regression Results                                
Dep. Variable:            expenditure   R-squared (uncentered):                   0.833
Model:                            OLS   Adj. R-squared (uncentered):              0.833
Method:                 Least Squares   F-statistic:                              2192.
Date:                Mon, 06 Oct 2025   Prob (F-statistic):                        0.00
Time:                        11:52:00   Log-Likelihood:                         -8335.6
No. Observations:                1319   AIC:                                  1.668e+04
Df Residuals:                    1316   BIC:                                  1.669e+04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

client_name  expenditure_prev
0       Lori Adams        214.382695
1     Ann Hamilton         47.804039
2  James Mcpherson        477.299762

## 1.4. Empregue agora um modelo equivalente (mesmos regressores) mais robusto, o `TheilSen Regressor`. Qual o seu **$R2$**? É maior que o anterior? Qual o valor de despesa de `Ann Hamilton` nesse novo modelo?

In [ ]:
from sklearn.linear_model import HuberRegressor, Ridge, TheilSenRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

# Split data into training and testing sets for regression
X = df[['income', 'share', 'months']] # Select the significant features
y = df['expenditure']

# Robust Regression (Huber Regressor)
huber = TheilSenRegressor(fit_intercept=False)
huber.fit(X, y)
y_pred_huber = huber.predict(X)
r2_huber = r2_score(y, y_pred_huber)
print(f"R2 score for Huber Regressor: {r2_huber:.4f}")

# Ridge Regression
ridge = Ridge(fit_intercept=False)
ridge.fit(X, y)
y_pred_ridge = ridge.predict(X)
r2_ridge = r2_score(y, y_pred_ridge)
print(f"R2 score for Ridge Regressor: {r2_ridge:.4f}")

# Compare with OLS R2 from previous steps
# You can get the R2 from the OLS results object 'results' in the previous cell 'jMHZvJ-vlKM9'
ols_r2 = results.rsquared # Access R-squared from the OLS results
print(f"R2 score for OLS: {ols_r2:.4f}")

# Predict for the case data using the new models
df_case_regression_selected = df_case_regression[['income', 'share', 'months']] # Select the same features

df_case_regression['expenditure_prev_huber'] = huber.predict(df_case_regression_selected)
df_case_regression['expenditure_prev_ridge'] = ridge.predict(df_case_regression_selected)

df_case_regression['expenditure_prev_OLS'] = results.predict(df_case_regression)

print("\nPredictions for the case data:")
display(df_case_regression[['client_name', 'expenditure_prev_OLS', 'expenditure_prev_huber', 'expenditure_prev_ridge']])

R2 score for Huber Regressor: 0.6943
R2 score for Ridge Regressor: 0.7529
R2 score for OLS: 0.8332

Predictions for the case data:


client_name  expenditure_prev_OLS  expenditure_prev_huber  \
0       Lori Adams            214.382695              155.917989   
1     Ann Hamilton             47.804039                7.555382   
2  James Mcpherson            477.299762              387.913632   

   expenditure_prev_ridge  
0              211.797712  
1               52.991929  
2              463.497157

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate RMSE for OLS model on X_train
y_pred_ols_train = results.predict(X)
rmse_ols_train = np.sqrt(mean_squared_error(y, y_pred_ols_train))
print(f"RMSE for OLS on Training Data: {rmse_ols_train:.4f}")

# Calculate RMSE for Huber Regressor on X_train
y_pred_huber_train = huber.predict(X)
rmse_huber_train = np.sqrt(mean_squared_error(y, y_pred_huber_train))
print(f"RMSE for Huber Regressor on Training Data: {rmse_huber_train:.4f}")

# Calculate RMSE for Ridge Regressor on X_train
y_pred_ridge_train = ridge.predict(X)
rmse_ridge_train = np.sqrt(mean_squared_error(y, y_pred_ridge_train))
print(f"RMSE for Ridge Regressor on Training Data: {rmse_ridge_train:.4f}")



RMSE for OLS on Training Data: 134.3853
RMSE for Huber Regressor on Training Data: 150.4604
RMSE for Ridge Regressor on Training Data: 135.2758


# Exercício 2. Classificação.

Implemente um modelo de `Knn` e um de `Árvore de Decisão` para a classificação da classe `card` empregando os **5 atributos preditores com maior ganho de informação** (informação mútua, empregando `random_state=42` para calcular).

* **Valores ausentes**. Segue mesma lógica de substituição do exercício anterior, incluindo o `seed=42`.

* **Normalização**. Em ambos os casos normalize os dados com a normalização `Standard Scaler`.

* **Conjuntos de Treinamento e Teste**. Empregue 25% de dados de teste, mantendo nos conjuntos a mesma distribuição dos valores de `card` e `random_state=42`.

* **Outros parâmetros**. Na **Árvore de Decisão**, empregue `random_state=42`, e no **Knn**, **6 vizinhos** mais próximos. Mantenha os demais parâmetros inalterados.





### 2.1. Quais os atributos com maior ganho de informação selecionados e quais são os seus valores?



In [ ]:
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Separate features (X) and target (y)
X = df.drop(['card', 'client_name'], axis=1)
y = df['card']

# Identify categorical features
categorical_cols = X.select_dtypes(include=['object']).columns

# Apply one-hot encoding to categorical features for mutual information calculation
# We use get_dummies here for simplicity in this specific context,
# not necessarily for downstream model training.
for c in categorical_cols:
    X[c] = LabelEncoder().fit_transform(X[c])

# Calculate mutual information scores
mutual_info = mutual_info_classif(X, y, random_state=42)

# Create a pandas Series for better visualization of scores
mutual_info_series = pd.Series(mutual_info, index=X.columns)

# Sort the scores in descending order
mutual_info_series.sort_values(ascending=False, inplace=True)

# Display the mutual information scores
print("Mutual Information Scores for features:")
display(mutual_info_series)

Mutual Information Scores for features:


expenditure    0.465650
share          0.396184
reports        0.122512
months         0.024070
age            0.016086
income         0.009143
owner          0.007383
majorcards     0.003912
dependents     0.000939
selfemp        0.000000
active         0.000000
sex            0.000000
dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

predictors = list(mutual_info_series.index[0:4])
X = df[predictors]
y = df['card']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.25, random_state=42)
X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(X_train)
X_train = pd.DataFrame(scaled_data, columns=X_train.columns)

scaled_data = scaler.transform(X_test)
X_test = pd.DataFrame(scaled_data, columns=X_test.columns)

display(X_train.head())
display(X_test.head())

expenditure     share   reports    months
0    -0.559640 -0.617962 -0.344811 -0.598500
1    -0.469693 -0.513023 -0.344811  1.312448
2    -0.180276 -0.093267 -0.344811 -0.779710
3    -0.002439  0.011672 -0.344811 -0.763236
4    -0.313871 -0.093267 -0.344811 -0.236078

expenditure     share   reports    months
0    -0.615674 -0.617962 -0.344811 -0.796184
1    -0.664242 -0.722900  1.888935  1.510132
2    -0.605242 -0.617962 -0.344811 -0.071342
3    -0.491325 -0.513023 -0.344811 -0.367868
4    -0.664242 -0.722900 -0.344811 -0.664394

### 2.2. Qual a acuracidade de cada um dos modelos obtidos e qual o **melhor modelo** (critério de acuracidade)?



### 2.3. No **pior modelo** (critério de acuracidade), qual o valor de classe que apresenta mais Falsos Positivos, e qual é essa quantidade?

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# Initialize the models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'KNN k=6': KNeighborsClassifier(n_neighbors=6),
    'Decision Tree': DecisionTreeClassifier(random_state=42)
}

# Train and evaluate each model
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy
    print(f'{name} Accuracy: {accuracy:.4f}')
    confusion = confusion_matrix(y_test, y_pred)
    print("\nMatriz de Confusão:\n", confusion)
    print()
    print(classification_report(y_test, y_pred))

# Optional: Print the best model
best_model_name = max(results, key=results.get)
print(f'\nBest model based on accuracy: {best_model_name}')

Logistic Regression Accuracy: 0.9152

Matriz de Confusão:
 [[232  20   0]
 [  4  70   0]
 [  4   0   0]]

              precision    recall  f1-score   support

        high       0.97      0.92      0.94       252
         low       0.78      0.95      0.85        74
      medium       0.00      0.00      0.00         4

    accuracy                           0.92       330
   macro avg       0.58      0.62      0.60       330
weighted avg       0.91      0.92      0.91       330

KNN k=6 Accuracy: 0.8970

Matriz de Confusão:
 [[233  19   0]
 [ 11  63   0]
 [  4   0   0]]

              precision    recall  f1-score   support

        high       0.94      0.92      0.93       252
         low       0.77      0.85      0.81        74
      medium       0.00      0.00      0.00         4

    accuracy                           0.90       330
   macro avg       0.57      0.59      0.58       330
weighted avg       0.89      0.90      0.89       330

Decision Tree Accuracy: 0.9424

Matriz

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/m

### 2.4. Qual a predição dos casos de `df_case_classification` empregando o melhor modelo? Qual a probalidade de cada valor de classe para a predição para `Kevin Hunter` e `Catherine Turner`?



In [ ]:
np.random.seed(42)
c = 'months'
display(df_case_classification[ df_case_classification.isna().any(axis=1) ])

for sex in df_case_classification.sex.unique():

  isna_by_sex = (df_case_classification[c].isna()) & (df['sex'] == sex)
  notna_by_sex = (~df[c].isna()) & (df['sex'] == sex)

  non_null_values = df[notna_by_sex][c]

  # Use np.random.choice with replacement to sample from non_null_values
  sampled_values = np.random.choice(non_null_values, size=sum(isna_by_sex), replace=True)

  # Fill the NaN values in the 'age' column with the sampled values
  df_case_classification.loc[isna_by_sex, c] = sampled_values

display(df_case_classification[ df_case_classification.isna().any(axis=1) ])


reports  age  income  share  expenditure owner selfemp  dependents  months  \
0        0   32    3.37   0.07       185.06    no      no           0     NaN   

   majorcards  active   client_name   sex  
0           0       6  Kevin Hunter  Male

Empty DataFrame
Columns: [reports, age, income, share, expenditure, owner, selfemp, dependents, months, majorcards, active, client_name, sex]
Index: []

In [ ]:
# Select the same features used for training
X_case_classification = df_case_classification[predictors]

# Scale the case data using the same scaler fitted on the training data
X_case_classification_scaled = scaler.transform(X_case_classification)
X_case_classification_scaled = pd.DataFrame(X_case_classification_scaled, columns=X_case_classification.columns)

# Get the best model (Decision Tree)
best_model = models['Decision Tree']

# Make predictions on the scaled case data
df_case_classification['card_predicted'] = best_model.predict(X_case_classification_scaled)

# Display the client names and their predicted card class
print("Predicted card class for clients in df_case_classification:")
display(df_case_classification[['client_name', 'card_predicted']])

Predicted card class for clients in df_case_classification:


client_name card_predicted
0      Kevin Hunter           high
1  Catherine Turner            low
2      Jeremy Pratt           high

In [ ]:
best_model.predict_proba(X_case_classification_scaled)

array([[1.   , 0.   , 0.   ],
       [0.125, 0.875, 0.   ],
       [1.   , 0.   , 0.   ]])

# Teoria

In [ ]:
import numpy as np

# Define the possible categories
categories = ['cat', 'dog', 'bird']
list_size = 200
disagreement_rate = 0.20

# Create the 'Actual' list with random values
np.random.seed(case) # for reproducibility
Actual = np.random.choice(categories, size=list_size, replace=True).tolist()

# Create the 'Predicted' list
Predicted = []
for i in range(list_size):
    if np.random.rand() < disagreement_rate:
        # Choose a different category for predicted
        other_categories = [cat for cat in categories if cat != Actual[i]]
        Predicted.append(np.random.choice(other_categories))
    else:
        # Make predicted match actual
        Predicted.append(Actual[i])

# Optional: Verify the disagreement rate (approximately)
# disagreement_count = sum([1 for a, p in zip(Actual, Predicted) if a != p])
# print(f"Approximate disagreement rate: {disagreement_count / list_size:.2f}")

print("Generated 'Actual' and 'Predicted' lists.")

Generated 'Actual' and 'Predicted' lists.


In [ ]:
confusion_matrix(Actual,Predicted)

array([[55,  7,  9],
       [ 9, 54,  2],
       [ 1,  9, 54]])

In [ ]:
print(classification_report(Actual,Predicted))

              precision    recall  f1-score   support

        bird       0.85      0.77      0.81        71
         cat       0.77      0.83      0.80        65
         dog       0.83      0.84      0.84        64

    accuracy                           0.81       200
   macro avg       0.82      0.82      0.82       200
weighted avg       0.82      0.81      0.82       200

